name: build ccapi_cli

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install dependencies (windows)
        if: runner.os == 'Windows'
        run: |
          vcpkg install libarchive:x64-windows

      - name: install dependencies (linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-dev libcurl4-openssl-dev

      - name: install dependencies (macos)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install libarchive curl

      - name: config cmake (windows)
        if: runner.os == 'Windows'
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="C:/Program Files/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: config cmake (macos and linux)
        if: runner.os != 'Windows'
        run: cmake -S . -B build

      - name: build
        run: cmake --build build --config Release